# Generated by Django 3.0.5 on 2020-08-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('polling_stations', models.IntegerField(null=True)),
                ('female_voters', models.IntegerField(null=True)),
                ('male_voters', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('population', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Constituency',
            },
        ),
        migrations.CreateModel(
            name='ConstituencyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Constituency Category',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('polling_stations', models.IntegerField(null=True)),
                ('female_voters', models.IntegerField(null=True)),
                ('male_voters', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('popn', models.IntegerField(null=True)),
                ('country_update_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectoralPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Electoral Position',
            },
        ),
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Parties',
            },
        ),
        migrations.CreateModel(
            name='PoliticianCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, null=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.ConstituencyCategory')),
            ],
            options={
                'verbose_name_plural': 'Politician Category',
            },
        ),
        migrations.CreateModel(
            name='PoliticianEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.CharField(max_length=100, null=True)),
                ('o_level', models.CharField(max_length=100, null=True)),
                ('high_school', models.CharField(max_length=100, null=True)),
                ('tertiary_or_University', models.CharField(max_length=100, null=True)),
                ('date_from', models.DateTimeField(null=True)),
                ('date_to', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Politician Education',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('polling_stations', models.IntegerField(null=True)),
                ('female_voters', models.IntegerField(null=True)),
                ('male_voters', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('numberOfVoters', models.IntegerField()),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Constituency')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.District')),
            ],
        ),
        migrations.CreateModel(
            name='Politicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician_status', models.CharField(choices=[('INCUMBENT', 'INCUMBENT'), ('FIRST TIME CONTESTANT', 'FIRST TIME CONTESTANT'), ('CONTESTED BEFORE', 'CONTESTED BEFORE')], max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('other_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('DOB', models.DateTimeField(null=True)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('DIVORCED', 'DIVORCED')], max_length=300, null=True)),
                ('children', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.PoliticianCategory')),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Constituency')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Country')),
                ('education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.PoliticianEducation')),
                ('electoral_positions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.ElectoralPositions')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Parties')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Regions')),
            ],
            options={
                'verbose_name_plural': 'Politician',
            },
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VotesCasted', models.IntegerField(null=True)),
                ('InvalidVotes', models.IntegerField(null=True)),
                ('totalVotes', models.IntegerField(null=True)),
                ('votesObtained', models.IntegerField(null=True)),
                ('resultsForm', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('CandidateName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Politicians')),
                ('Constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.Constituency')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.District')),
                ('electoral_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.ElectoralPositions')),
                ('pollingStation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.PollingStation')),
            ],
            options={
                'verbose_name_plural': 'Election Results',
            },
        ),
        migrations.AddField(
            model_name='constituency',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.ConstituencyCategory'),
        ),
        migrations.AddField(
            model_name='constituency',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elections.District'),
        ),
    ]
