# Generated by Django 3.0.8 on 2020-08-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituency',
            old_name='female_voters',
            new_name='femaleVoters',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='male_voters',
            new_name='maleVoters',
        ),
        migrations.RenameField(
            model_name='constituency',
            old_name='polling_stations',
            new_name='pollingStations',
        ),
        migrations.RemoveField(
            model_name='constituency',
            name='create_date',
        ),
    ]
