# Generated by Django 3.0.8 on 2020-08-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20200824_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='acronym',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
